---
name: Clippy

# Trigger the workflow on push or pull request
"on":
  push:
  pull_request:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: "Run clippy"
        run: cargo clippy --all-targets
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
