---
name: Rust Testing
"on":
  push:
  pull_request:
env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cargo_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.8
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install typical dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            libssl-dev
      - name: "Run cargo test"
        run: cargo test
      - name: "Run cargo clippy"
        run: cargo clippy
      - name: "Build the workspace"
        run: cargo build --workspace
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
