---
name: mypy

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  mypy: # don't rename, used for rulesets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
      - name: Running type checking
        run: |
          mise run ty
