---
name: Python Linting

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - name: Running ruff checks
        run: |
          mise ruff
