name: test the things

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Running tests
        uses: fylein/python-pylint-github-action@v4
        with:
          args: |
            python3 -m pip install --quiet --upgrade flit pytest pylint
            FLIT_ROOT_INSTALL=1 python3 -m flit install --deps all
            python3 -m pylint --rcfile=.pylintrc github_linter

      - name: Running tests
        uses: fylein/python-pylint-github-action@v4
        with:
          args: |
            python3 -m pip install --no-cache-dir --quiet --upgrade flit
            FLIT_ROOT_INSTALL=1 python3 -m flit install
            ./run_pylint.sh
  mypy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Running mypy
        uses: fylein/python-pylint-github-action@v4
        with:
          args: |
            python3 --version
            python3 -m pip install --quiet --no-cache-dir --upgrade flit
            FLIT_ROOT_INSTALL=1 python3 -m flit install
            ./run_mypy.sh
  pytest:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Running pytest
        uses: fylein/python-pylint-github-action@v4
        with:
          args: |
            python3 --version
            python3 -m pip install --quiet --no-cache-dir --upgrade flit
            FLIT_ROOT_INSTALL=1 python3 -m flit install
            python3 -m pytest
