name: Build / Test

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Running tests
        run: |
            python -m pip install --no-cache-dir --quiet --upgrade flit
            FLIT_ROOT_INSTALL=1 python -m flit install
            ./run_pylint.sh
  mypy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Running mypy
        run: |
          python --version
          python -m pip install --quiet --no-cache-dir --upgrade flit
          FLIT_ROOT_INSTALL=1 python -m flit install
          ./run_mypy.sh

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC2148
  # pytest:
  #   runs-on: ubuntu-latest
  #   concurrency:
  #     group: ${{ github.workflow }}-${{ github.ref }}
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
  #     - name: Set up Python 3
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.9'
  #     - name: Installing Flit and PIP
  #       run: |
  #         python -m pip install --quiet --no-cache-dir --upgrade flit
  #     - name: Installing Dependencies
  #       run: |
  #         FLIT_ROOT_INSTALL=1 python -m flit install
  #     - name: Running pytest
  #       run: |
  #         python -m pytest
