---
name: pylint

"on":
  push:
    branches:
      - main # Set a branch to deploy
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3.12 # TODO: This should be template-able based on what's in pyproject
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # TODO: This should be template-able based on what's in pyproject
      - name: Running tests
        run: |
          python --version
          python -m pip install --quiet --no-cache-dir --upgrade uv
          uv run ruff check $(basename $(pwd) | sed -E 's/-/_/g') tests
